pull_request_rules: []
merge_protections:
  - name: VM7 config-change protection
    if: []
    success_conditions: []
merge_protections_settings:
  auto_merge_conditions:
    - mergify-configuration-changed
